### ISSUE TITLE
ライセンスの追加を検討してください

### ISSUE THREAD

**Issue by engineerjoe440** [tomo-makes/marp-styles#1]
壊れた言語を許してください。私は変換を支援するためにGoogle翻訳を使用しています。
他の人がサンプルMarpテーマを利用できるように、リポジトリにライセンスを追加することを検討してほしいと思っていました。ありがとうございました！

**Comment by tomo-makes** [comment]
Thanks, I have just added the LICENSE file to this repository. ライセンスファイルを追加しました。
